// <auto-generated />
using System;
using InstaPersistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InstaPersistence.Migrations
{
    [DbContext(typeof(InstaDbContext))]
    [Migration("20230216235757_ProtectedInstaUsersAdded")]
    partial class ProtectedInstaUsersAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InstaDomain.InstaUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Followers")
                        .HasColumnType("integer");

                    b.Property<int>("Following")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FollowingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFollower")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UnfollowingDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Name"), new[] { "IsFollower", "Status" });

                    b.ToTable("InstaUsers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Followers = 0,
                            Following = 0,
                            IsFollower = true,
                            Name = "hidethetrack123",
                            Rank = 0,
                            Status = 3
                        },
                        new
                        {
                            Id = 2L,
                            Followers = 0,
                            Following = 0,
                            IsFollower = true,
                            Name = "dr.lilith",
                            Rank = 0,
                            Status = 3
                        },
                        new
                        {
                            Id = 3L,
                            Followers = 0,
                            Following = 0,
                            IsFollower = true,
                            Name = "dr.imiller",
                            Rank = 0,
                            Status = 3
                        },
                        new
                        {
                            Id = 4L,
                            Followers = 0,
                            Following = 0,
                            IsFollower = true,
                            Name = "mynameiswhm",
                            Rank = 0,
                            Status = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
